#Specify the data base driver(Here use the Mysql database) in te dev-profile
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_boot
      username: root
      password: Bishnu@123
      dbcp2:
         min-idle: 10
         max-total: 100
         max-wait-millis: 60000
#Sepcify the datasource(dbcp2 data source used) in the dev-profile
      type: org.apache.commons.dbcp2.BasicDataSource

